language: python
python:
  - "3.5.2"
install:
  - pip install python-dateutil
script:
  - git clone https://github.com/Twentysix26/Red-DiscordBot red
  - cp ./*/*.py ./red/cogs
  - python -m compileall ./red/cogs
cache: pip
notifications:
  email: false
